server:
  port: 9090
c3p0:
  datasource:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/springboot
    user: root
    password: 123
    minPoolSize: 3
    maxPoolSize: 100
    initialPoolSize: 3
